input_text_desired_length: 110
input_text_max_length: 170
selected_theme: freddyaboulton/dracula_revamped
server_name: '0.0.0.0'
server_port: 9336
server_share: true
silence_between_sentences: 250
silence_between_speakers: 500
